name: CI/CD production front-end pipeline

on:
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/**"

env:
  AWS_REGION: us-east-1
  SOURCE_DIST: ./web/dist
  AWS_BUCKET_NAME_CDN: brev-ly-cdn-bucket
  BUCKET_NAME: brev-ly-bucket

jobs:
  code-quality:
    runs-on: ubuntu-latest

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        working-directory: ./web
        run: pnpm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NODE_ENV: "production"
          envkey_VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL }}
          envkey_VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          directory: "./web" # Pasta onde criar o .env
          file_name: ".env"
          fail_on_empty: true
          sort_keys: false

      - name: set id commit sha
        id: generate-tag
        run: |
          echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Build front-end
        working-directory: ./web
        run: pnpm build

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDN S3 sync
        id: s3-sync-cdn
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_BUCKET_NAME_CDN }}/ --delete --exclude '*.git*'

      - name: Invoke CDN invalidation
        id: invalidation-cdn
        run: |
          aws cloudfront create-invalidation --distribution-id ${cloudfront_distribution_id} --paths '/*'
